apiVersion: zitadel.m.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: billing-worker
  namespace: zitadel
spec:
  providerConfigRef:
    name: zitadel
    kind: ProviderConfig
  forProvider:
    organizationRef:
      name: platform
    name: Billing Worker
    userName: billing-worker
    description: Background worker of the billing application
    accessTokenType: Jwt
---
apiVersion: zitadel.m.crossplane.io/v1alpha1
kind: PersonalAccessToken
metadata:
  name: billing-worker-pat
  namespace: zitadel
spec:
  providerConfigRef:
    name: zitadel
    kind: ProviderConfig
  writeConnectionSecretToRef:
    name: billing-worker-pat
  forProvider:
    userRef:
      name: billing-worker
