/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package common

import (
	"reflect"
	"strconv"

	"github.com/loafoe/provider-zitadel/internal/clients/zitadel"
)

// IsZitadelID reports whether s looks like an ID generated by Zitadel. Zitadel
// IDs are numeric, which lets the controllers tell them apart from an external
// name that a user set by hand.
func IsZitadelID(s string) bool {
	if s == "" {
		return false
	}

	_, err := strconv.ParseUint(s, 10, 64)

	return err == nil
}

// Recover looks an external resource up again, which is needed whenever the
// external name of a managed resource cannot be trusted:
//
//   - On a normal reconcile the external name annotation holds the Zitadel ID
//     of the resource.
//   - After the annotation was lost - or when the user pinned a custom ID
//     through spec.forProvider.id - the resource is looked up by that ID.
//   - A user supplied (non numeric) external name is never resolved: the
//     resource may or may not exist, and the reconciler will (re)create it if
//     Zitadel does not know it.
//
// byName is the last resort: it searches the resource by name within its
// organization or project, which is what makes the provider idempotent across
// provider restarts and Crossplane reinstalls.
//
// It returns the found resource and true, or the zero value and false when the
// resource does not exist.
func Recover[T any](externalName, pinnedID string, byID func(string) (T, error), byName func() (T, error)) (T, bool, error) {
	var zero T

	switch {
	case externalName != "":
		if !IsZitadelID(externalName) {
			// A user supplied external name cannot be resolved.
			return zero, false, nil
		}

		return lookup(byID, externalName)

	case pinnedID != "":
		return lookup(byID, pinnedID)

	default:
		res, err := byName()
		if err != nil {
			return zero, false, err
		}

		// byName signals "not found" by returning a nil pointer. Storing it in
		// the type parameter boxes a typed nil, which is not equal to a nil
		// interface, so the check has to be done on the value itself.
		if isNil(res) {
			return zero, false, nil
		}

		return res, true, nil
	}
}

// isNil reports whether v is a nil pointer, map, slice, interface, channel or
// function.
func isNil[T any](v T) bool {
	rv := reflect.ValueOf(&v).Elem()

	switch rv.Kind() { //nolint:exhaustive // all other kinds can never be nil
	case reflect.Pointer, reflect.Map, reflect.Slice, reflect.Interface, reflect.Chan, reflect.Func, reflect.UnsafePointer:
		return rv.IsNil()
	}

	return false
}

// lookup resolves a single ID, translating a Zitadel not-found into a plain
// "does not exist" result.
func lookup[T any](byID func(string) (T, error), id string) (T, bool, error) {
	var zero T

	res, err := byID(id)
	if err == nil {
		return res, true, nil
	}

	if zitadel.IsNotFound(err) {
		return zero, false, nil
	}

	return zero, false, err
}
